### ISSUE TITLE
启动服务报错

### ISSUE THREAD

**Issue by navee** [hustcc/redis-monitor#1]
```
Traceback (most recent call last):                                                               
  File "/usr/bin/gunicorn", line 9, in <module>                                                  
    load_entry_point('gunicorn==19.0.0', 'console_scripts', 'gunicorn')()                        
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 74, in run               
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()                                     
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 166, in run                 
    super(Application, self).run()                                                               
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 71, in run                  
    Arbiter(self).run()                                                                          
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 169, in run                  
    self.manage_workers()                                                                        
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 477, in manage_workers       
    self.spawn_workers()                                                                         
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 537, in spawn_workers        
    time.sleep(0.1 * random.random())                                                            
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 209, in handle_chld          
    self.reap_workers()                                                                          
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 459, in reap_workers         
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)                                             
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>                              
```

貌似是
```
gunicorn --worker-class=gevent -w 4 -b 0.0.0.0:7259 run_monitor:app &
```
这句命令不对造成的。（python不熟，无力解决，逃。。）

顺便提2个坑
1.pip无法安装 sqlite3，pip列表里面只有sqlitedatabase
2.安装gevent 需要 python-dev依赖

**Comment by hustcc** [comment]
目测是gevent的问题，如果是在不行，就用python run_monitor.py来运行吧~

**Comment by qq2867234** [comment]
Could not find a version that satisfies the requirement sqlite3 (from -r requirements.txt (line 6)) (from versions: )
No matching distribution found for sqlite3 (from -r requirements.txt (line 6))

**Comment by qq2867234** [comment]
Could not find a version that satisfies the requirement sqlitedatabase (from -
r requirements.txt (line 1)) (from versions: )
No matching distribution found for sqlitedatabase (from -r requirements.txt (lin
e 1))

sqlitedatabase 也没有呢。

**Comment by hustcc** [comment]
先安装一下sqlite3吧，请看最新版本的readme文件。

**Comment by hustcc** [comment]
是否已经解决问题，如果解决，可以关闭issue，如果没有解决，是否需要帮助？

**Comment by navee** [comment]
还是python依赖缺失造成的！
使用python run_monitor.py 运行，根据报错安装了如下python依赖：
werkzeug
jinja2
itsdangerous

python run_monitor.py 运行成功！run_monitor运行成功！
